### ISSUE TITLE
Not working with Ubuntu

### ISSUE THREAD

**Issue by mahmoudfelfel** [jamesryanbell/node-wraith#6]
Hi, thanks for the great work, i was searching for any node implementation for wraith and found yours, but it's not working for me on Ubuntu
This command 
```
wraith --config ./config/chrome
```
gives me this error
```
module.js:338
    throw err;
          ^
Error: Cannot find module './config/chrome'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/wraith/cli.js:20:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by mahmoudfelfel** [comment]
And this what i'm getting with ```npm install```
http://pastebin.com/jbCk9kFu

**Comment by mahmoudfelfel** [comment]
Ok it is working now, i was referring to the wrong config file, sorry !
